# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-12-29 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='com_name',
            field=models.CharField(default='auto name', max_length=200, verbose_name='公司名称'),
            preserve_default=False,
        ),
    ]
