# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-12-29 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobinfo_com_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='detail',
            field=models.TextField(blank=True, verbose_name='详细介绍'),
        ),
    ]
