# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-12-31 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_jobinfo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='status',
            field=models.IntegerField(choices=[(1, '在线'), (2, '离线')], default=1, verbose_name='状态'),
        ),
    ]
