# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-02-11 00:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers.director.model_func.cus_fields.cus_picture


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_companyinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='jobinfo',
            name='com_name',
        ),
        migrations.RemoveField(
            model_name='jobinfo',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='jobinfo',
            name='publisher',
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='audit_status',
            field=models.IntegerField(choices=[(1, '未审批'), (2, '审批中'), (3, '审批通过')], default=1, verbose_name='审批状态'),
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='bid',
            field=helpers.director.model_func.cus_fields.cus_picture.PictureField(blank=True, max_length=300, verbose_name='中标书'),
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='com',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.CompanyInfo', verbose_name='发布商家'),
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='contract',
            field=helpers.director.model_func.cus_fields.cus_picture.PictureField(blank=True, max_length=300, verbose_name='合同'),
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='plat_contract',
            field=helpers.director.model_func.cus_fields.cus_picture.PictureField(blank=True, help_text='请在[资料下载]中下载模板', max_length=300, verbose_name='服务合同'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='status',
            field=models.IntegerField(choices=[(0, '编辑中'), (1, '审批中'), (2, '审批通过')], default=0, verbose_name='当前状态'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='status',
            field=models.IntegerField(choices=[(1, '在线'), (2, '离线')], default=1, verbose_name='在线状态'),
        ),
    ]
