# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-02-12 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_workinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeekJobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.CharField(blank=True, max_length=200, verbose_name='薪资要求')),
                ('jobtime', models.CharField(blank=True, max_length=200, verbose_name='可以上班时间')),
                ('key_words', models.CharField(blank=True, max_length=100, verbose_name='关键字')),
                ('desp', models.TextField(blank=True, verbose_name='详细描述')),
                ('status', models.IntegerField(choices=[(1, '在线'), (2, '离线')], default=1, verbose_name='在线状态')),
                ('audit_status', models.IntegerField(choices=[(1, '未审批'), (2, '审批中'), (3, '审批通过')], default=1, verbose_name='审批状态')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.WorkInfo', verbose_name='求职者')),
            ],
        ),
    ]
