# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-02-16 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_seekjobinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinfo',
            name='contact',
            field=models.CharField(blank=True, max_length=200, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='姓名'),
        ),
    ]
