# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-02-18 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import helpers.director.model_func.cus_fields.cus_picture


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_auto_20200216_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinfo',
            name='head',
            field=helpers.director.model_func.cus_fields.cus_picture.PictureField(blank=True, max_length=300, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='seekjobinfo',
            name='key_words',
            field=models.CharField(blank=True, help_text='最多不超过30个字', max_length=30, verbose_name='关键字'),
        ),
    ]
