# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-02-18 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_auto_20200218_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seekjobinfo',
            old_name='udpate_time',
            new_name='update_time',
        ),
    ]
