# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-02-19 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import helpers.director.model_func.cus_fields.cus_picture
import helpers.director.model_func.cus_fields.richtext


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_auto_20200219_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyHelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('content', helpers.director.model_func.cus_fields.richtext.RichtextField(verbose_name='内容')),
            ],
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='address',
            field=models.CharField(blank=True, max_length=400, verbose_name='公司地址'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='contact',
            field=models.CharField(max_length=200, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='contact',
            field=models.CharField(blank=True, max_length=200, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='head',
            field=helpers.director.model_func.cus_fields.cus_picture.PictureField(blank=True, help_text='2寸标准证件照', max_length=300, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='id_face2',
            field=helpers.director.model_func.cus_fields.cus_picture.PictureField(blank=True, max_length=300, verbose_name='身份证反面'),
        ),
    ]
