# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-02-20 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_auto_20200219_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinfo',
            name='service_agreement',
        ),
    ]
