# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-02-22 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_remove_workinfo_service_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='key_words',
            field=models.CharField(default='', help_text='最多不超过30个字', max_length=30, verbose_name='关键字'),
        ),
    ]
