# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-05-26 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import helpers.director.model_func.cus_fields.cus_picture


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_jobinfo_key_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinfo',
            name='bank_code',
            field=models.CharField(blank=True, max_length=300, verbose_name='卡号'),
        ),
        migrations.AddField(
            model_name='workinfo',
            name='bank_cover',
            field=helpers.director.model_func.cus_fields.cus_picture.PictureField(blank=True, max_length=300, verbose_name='银行卡正面'),
        ),
        migrations.AddField(
            model_name='workinfo',
            name='opening_bank',
            field=models.CharField(blank=True, max_length=400, verbose_name='开户行'),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='status',
            field=models.IntegerField(choices=[(0, '离线'), (1, '在线')], default=1, verbose_name='在线状态'),
        ),
        migrations.AlterField(
            model_name='seekjobinfo',
            name='status',
            field=models.IntegerField(choices=[(0, '离线'), (1, '在线')], default=1, verbose_name='在线状态'),
        ),
    ]
