# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-06-09 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_applyrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyrecord',
            name='company',
        ),
        migrations.AddField(
            model_name='applyrecord',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='job.SeekJobInfo', verbose_name='申请职位'),
            preserve_default=False,
        ),
    ]
