# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-06-09 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_auto_20200609_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyrecord',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.JobInfo', verbose_name='申请职位'),
        ),
        migrations.AlterField(
            model_name='applyrecord',
            name='status',
            field=models.IntegerField(choices=[(0, '申请'), (1, '同意'), (2, '完结')], default=0, verbose_name='状态'),
        ),
    ]
