# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-06-11 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_auto_20200609_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyrecord',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applyrecord',
            name='status',
            field=models.IntegerField(choices=[(0, '未读'), (1, '已读')], default=0, verbose_name='状态'),
        ),
    ]
