# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-07-08 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0024_auto_20200611_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='appoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.WorkInfo', verbose_name='指定工人'),
        ),
        migrations.AlterField(
            model_name='applyrecord',
            name='status',
            field=models.IntegerField(choices=[(0, '待商户查看'), (1, '接受申请/待平台审批'), (3, '平台审批通过'), (4, '商户确定工作完成'), (5, '平台已结算'), (2, '拒绝申请'), (101, '平台审批不通过')], default=0, verbose_name='状态'),
        ),
    ]
