# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-07-08 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0025_auto_20200708_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='admin_fee',
            field=models.IntegerField(default=0, verbose_name='管理费'),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='pay',
            field=models.IntegerField(default=0, verbose_name='支付费用'),
        ),
    ]
