# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-07-17 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0026_auto_20200708_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyrecord',
            name='status',
            field=models.IntegerField(choices=[(0, '待商户查看'), (1, '商户接受申请'), (3, '平台审批通过'), (4, '商户确定工作完成'), (5, '平台已结算'), (2, '商户拒绝申请'), (101, '平台审批不通过')], default=0, verbose_name='状态'),
        ),
        migrations.RemoveField(
            model_name='jobinfo',
            name='appoint',
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='appoint',
            field=models.ManyToManyField(blank=True, to='job.WorkInfo', verbose_name='指定工人'),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='key_words',
            field=models.CharField(blank=True, help_text='最多不超过30个字', max_length=30, verbose_name='关键字'),
        ),
    ]
